version: 2
jobs:
  build:
    working_directory: ~/android-app/app
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "android-app/build.gradle" }}-{{ checksum  "android-app/app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: cd android-app && ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: cd android-app && ./gradlew lint test
      - store_artifacts:
          path: android-app/app/build/reports
          destination: reports
      - store_test_results:
          path: android-app/app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples    

