version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "~/code/android-app/build.gradle" }}-{{ checksum  "~/code/android-app/app/build.gradle" }}
      - run:
          name: Authenticate
          command: |
            sudo apt-get update 
            sudo apt-get --only-upgrade install kubectl google-cloud-sdk google-cloud-sdk-app-engine-grpc google-cloud-sdk-pubsub-emulator google-cloud-sdk-app-engine-go google-cloud-sdk-datastore-emulator google-cloud-sdk-app-engine-python google-cloud-sdk-cbt google-cloud-sdk-bigtable-emulator google-cloud-sdk-app-engine-python-extras google-cloud-sdk-datalab google-cloud-sdk-app-engine-java
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/code/android-app/app/google-services.json
            sudo gcloud auth activate-service-account --key-file ${HOME}/code/android-app/app/google-services.json
            sudo gcloud config set project $GCLOUD_SERVICE_KEY
      - run:
          name: Download Dependencies
          command: cd android-app && ./gradlew androidDependencies
      - run:
          name: Sanity Check
          command: ls
      - save_cache:
          paths:
            - ~/code/android-app/
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: cd android-app && ./gradlew lint test
      - store_artifacts:
          path: android-app/app/build/reports
          destination: reports
      - store_test_results:
          path: android-app/app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples    