version: 2
jobs:
  build:
    working_directory: ~/android-app/app
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "android-app/build.gradle" }}-{{ checksum  "android-app/app/build.gradle" }}
      - run:
          name: Authenticate
          command: echo $FIREBASE_SERVICE_ACCOUNT | base64 --decode --ignore-garbage > ${HOME}/android-app/app/study-slug-274435baf057.json
          command: sudo gcloud --quiet components update
          command: sudo gcloud auth activate-service-account --key-file ${HOME}/android-app/app/study-slug-274435baf057.json
          command: sudo gcloud config set project $FIREBASE_SERVICE_ACCOUNT
      - run:
          name: Download Dependencies
          command: cd android-app && ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/android-app/
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: cd android-app && ./gradlew lint test
      - store_artifacts:
          path: android-app/app/build/reports
          destination: reports
      - store_test_results:
          path: android-app/app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples    