version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "android-app/build.gradle" }}-{{ checksum  "android-app/app/build.gradle" }}
      - run:
          name: Authenticate
          command: |
            sudo apt-get update 
            sudo apt-get --only-upgrade install kubectl google-cloud-sdk google-cloud-sdk-app-engine-grpc google-cloud-sdk-pubsub-emulator google-cloud-sdk-app-engine-go google-cloud-sdk-datastore-emulator google-cloud-sdk-app-engine-python google-cloud-sdk-cbt google-cloud-sdk-bigtable-emulator google-cloud-sdk-app-engine-python-extras google-cloud-sdk-datalab google-cloud-sdk-app-engine-java 
            echo 'export FIREBASE_SERVICE_ACCOUNT="$FIREBASE_SERVICE_ACCOUNT"' >> $BASH_ENV
            echo $FIREBASE_SERVICE_ACCOUNT | base64 --decode --ignore-garbage > ${HOME}/code/android-app/app/gcloud-service-key.json
            sudo gcloud auth activate-service-account --key-file ${HOME}/code/android-app/app/gcloud-service-key.json
            sudo gcloud config set project $FIREBASE_PROJECT
      - run:
          name: Download Dependencies
          command: cd android-app && ./gradlew androidDependencies
      - run:
          name: Sanity Check
          command: ls
      - save_cache:
          paths:
            - android-app/
          key: jars-{{ checksum "android-app/build.gradle" }}-{{ checksum  "android-app/app/build.gradle" }}
      - run:
          name: Run Tests
          command: |
            echo 'export GOOGLE_SERVICES="$GOOGLE_SERVICES"' >> $BASH_ENV
            echo $GOOGLE_SERVICES | base64 --decode --ignore-garbage >${HOME}/code/android-app/app/google-services.json
            cd android-app
            ./gradlew lint test
      - store_artifacts:
          path: android-app/app/build/reports
          destination: reports
      - store_test_results:
          path: android-app/app/build/test-results
      - run:
          name: Build
          command: |
            cd android-app
            ./gradlew clean assembleRelease --no-daemon --stacktrace
      - store_artifacts:
          path: android-app/app/build/outputs/apk/
          destination: apks/
      - run:
          name: Deploy
          command: |
            echo 'export CIRCLE_BRANCH="$CIRCLE_BRANCH"' >> $BASH_ENV
            mv ${HOME}/code/android-app/app/build/outputs/apk/release/app-release-unsigned.apk ${HOME}/code/android-app/app/build/outputs/apk/release/$CIRCLE_BRANCH.apk
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples    